# ====config 设置====
# 依赖组件
plugins: [jekyll-paginate]

# 本地服务器 
host: 0.0.0.0
port: 4001

# 时区
timezone: Asia/Shanghai

# markdown语法
markdown: kramdown

# 根目录设置
# 如果是根目录, 不要填写'/', 直接留空就行
# 如果是非根目录访问, 如http://abc.com/blog, 此处填写'/blog'
baseurl:

# 分页设置
paginate: 50

# 分页形式
paginate_path: "page:num"

# 链接形式
permalink: /:year/:month/:day/:title.html


# ====site info 站点信息====
# 站点地址：用于本站链接及生成sitemap使用
# 例：http://example.com
website: http://collection.yukapril.com

# 标题: 在底部版权位置显示，以及页面meta标签（SEO）
title: 收藏集 - YUKAPRIL

# 站点描述和关键词 仅作用于页面meta标签使用(SEO)
description: YUKAPRIL 文章收集
keywords: YUKAPRIL 文章 收集 收藏集

# 备案信息
miibeian: 京ICP备15045677号-1